window.addEventListener('load', () => {
	require('./hero')
	require('./why')
	require('./market')
	require('./fees')
	require('./support')
	require('./road')
	require('./speaks')
	require('./team')
	require('./delivery')
	require('./details')
	require('./exchange')
	require('./news')
})